# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Change color palette
palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true
format = """$directory$character"""
right_format = """$all"""

[aws]
symbol = "  "

[battery]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

# Replace the '❯' symbol in the prompt with '➜' and change vimcmd symbol
[character]
vimcmd_symbol = '[V](bold green)'
vimcmd_replace_one_symbol = '[V](bold purple)'
vimcmd_replace_symbol = '[V](bold purple)'
vimcmd_visual_symbol = '[V](bold yellow)'

[cmd_duration]
disabled = true

[conda]
ignore_base = false

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 2
truncate_to_repo = false
use_os_path_sep = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os]
disabled = true

[php]
symbol = " "

[python]
symbol = " "
version_format = 'v${major}.${minor}'

[rlang]
symbol = '🅡 '

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
