import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
]

[window]
dynamic_title = false
blur = true
opacity = 0.975

[window.padding]
x = 5
y = 5

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "block"

[env]
TERM = "xterm-256color"
